drives:
  max-types: 128
hoppers:
  allow-input: true

items:
  1k:
    material: "PAPER"
    custom-model-data: 0
  4k:
    material: "PAPER"
    custom-model-data: 0
  16k:
    material: "PAPER"
    custom-model-data: 0
  64k:
    material: "PAPER"
    custom-model-data: 0