name: EnergeticStorage
main: net.seanomik.energeticstorage.EnergeticStorage
version: 0.8.0-SNAPSHOT
description: "EnergeticStorage is a plugin for managing energetic storage systems."
author: "SeanOMik, LiamXSage, Drak"
api-version: "1.21"
load: POSTWORLD
loader: net.seanomik.energeticstorage.DependencyLoader

dependencies:
  server:
    Multiverse-Core:
      required: false
      load: BEFORE
    BukkitOfUtils:
      required: true
      load: BEFORE
    NBTAPI:
      required: true
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
