name: '${name}'
version: '${version}'
main: '${main}'

api-version: "1.20"
folia-supported: true

authors:
  - SeanOMik
  - LiamXSage
  - Drak

depend:
  - NBTAPI
  - BukkitOfUtils
softdepend:
  - Multiverse-Core
  - PlaceholderAPI

commands:
  esgive:
    aliases:
    - egive
    permission: energeticstorage.give
    description: Give a Energetic Storage item.
  esreload:
    aliases:
    - ereload
    permission: energeticstorage.reload
    description: Reload all Energetic Storage configs.
